# Generated by Django 4.2 on 2024-04-18 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_board'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
